# Rúbrica de Evaluación para el Laboratorio 16 de Comunicaciones Inalámbricas

Esta rúbrica evalúa el criterio de desempeño "Diseña sistemas de software según requerimiento de la empresa" en el contexto del Laboratorio 16 del curso de Comunicaciones Inalámbricas. Se enfoca en la capacidad del estudiante para diseñar, construir y justificar soluciones a casos propuestos, abarcando desde el análisis de requisitos hasta la implementación, selección de componentes y verificación de funcionamiento. Los niveles de desempeño reflejan la Taxonomía de Bloom, evaluando desde el recuerdo básico hasta el análisis crítico y la resolución autónoma de problemas.

| Subcriterio de Evaluación | 4 - Sobresaliente (Analizar) | 3 - Competente (Aplicar) | 2 - Básico (Recordar / Comprender) | 1 - Insuficiente (No demuestra) |
| --- | --- | --- | --- | --- |
| Análisis y Justificación del Diseño | Deconstruye los requisitos del caso, compara múltiples enfoques y justifica un diseño óptimo de sistema de comunicación inalámbrica, explicando sus ventajas y limitaciones. | Aplica los conceptos del curso para diseñar una solución coherente y funcional, justificando las decisiones principales de diseño para el caso propuesto. | Identifica elementos clave del caso y propone un diseño básico, pero su justificación es limitada o contiene inconsistencias, demostrando una comprensión superficial. | No logra identificar los requisitos o proponer un diseño inicial, ni justificar ninguna parte de la solución. |
| Implementación de la Solución (Aspectos Técnicos) | Evalúa la complejidad técnica, organiza la implementación modularmente y diagnostica/resuelve problemas complejos de integración en la solución propuesta. | Construye una implementación funcional de la solución para el caso propuesto utilizando las herramientas y tecnologías adecuadas de comunicaciones inalámbricas. | Sigue los pasos básicos para implementar componentes, pero con errores de configuración o integración, mostrando una comprensión limitada de la interconexión. | No logra implementar los componentes técnicos fundamentales de la solución. |
| Selección y Configuración de Componentes de Comunicación | Compara y contrasta diferentes tecnologías y componentes de comunicación inalámbrica, seleccionando los óptimos y configurándolos para maximizar el rendimiento y la eficiencia. | Selecciona y configura correctamente los componentes de comunicación inalámbrica (ej. protocolos, frecuencias) para cumplir con los requisitos del caso propuesto. | Identifica algunos componentes de comunicación, pero la selección o configuración es incompleta o incorrecta, demostrando una comprensión básica de su función. | No logra seleccionar o configurar ningún componente de comunicación relevante para la solución. |
| Prueba y Verificación del Funcionamiento | Diseña y ejecuta pruebas rigurosas, analiza los resultados de manera crítica y propone optimizaciones o soluciones alternativas a los problemas detectados en el sistema. | Ejecuta pruebas para verificar el funcionamiento de la solución implementada y corrige los errores básicos para asegurar que cumple con los objetivos del caso. | Realiza pruebas superficiales o incompletas, y tiene dificultad para interpretar los resultados o identificar los fallos del sistema. | No realiza ninguna prueba o verificación del funcionamiento de la solución. |
